name: Generate test coverage report

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: Check coverage
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install mamba for quicker env updates 
        run: |
          conda install -c conda-forge mamba -y

      - name: Install dependencies
        run: |
          mamba env update --file environment_all_backends.yml --name base

        # have to run tests in top dir so python-coverage-comment can get report
      - name: Install conda develop and add source dir
        run: |
          conda install conda-build -y
          conda develop ./torchquad/

      - name: Install pytest and pytest-cov
        run: |
          conda install pytest pytest-cov -y

      - name: Launch tests & generate report
        run: $CONDA/bin/pytest

      - name: Coverage comment
        id: coverage_comment
        uses: ewjoachim/python-coverage-comment-action@v2
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERBOSE: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v2
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          # If you use a different name, update COMMENT_ARTIFACT_NAME accordingly
          name: python-coverage-comment-action
          # If you use a different name, update COMMENT_FILENAME accordingly
          path: python-coverage-comment-action.txt
